meshcloud/meshcloud-docs

docs/meshstack.azure.md, docs/meshstack.identity-federation.md
separate "integration decisions" from configuration tutorial
=> refactor: restructure azure operator docs

website/siteConfig.js
Add algolia search for documentation. apiKey apparently does not have to be kept secret (example from official docusaurus config https://github.com/facebook/docusaurus/blob/1c032a0bd95b7c95e1985ff104d43416c16714e1/website/docusaurus.config.js#L74)
=> feat(search): add algolia search

docs/meshstack.tag-schema.md
this information got lost while restructuring the tag docs
=> doc: deprecate cost center tag

docs/meshcloud.customer.md
Related to https://github.com/meshcloud/meshfed-release/pull/70. Although, this change is not about administrator rights for the Partner to view Groups within customers, but rather that the partner user can view his own groups (within the partner customer). So I did the change in meshcloud.customer.md and not administration.md.
=> feat: customer user groups viewing CU-5ynk53

docs/meshstack.gcp.index.md, docs/meshstack.gcp.landing-zones.md
Interestingly the rights suggestion for the SPN of the replicator itself seems correct.
=> Updates GCP rights for buckets and SPN

docs/administration.index.md, docs/meshcloud.customer.md, docs/meshcloud.index.md, docs/meshcloud.project.md, docs/meshstack.authorization.md, docs/meshstack.platform-location.md
With the introduction of the principal abstraction for users and groups, documentation around access control needed to be adapted.
I also used the term "principal" in the documentation so we can apply a ubiquitous language. We decided not to use it in the UI, but i think it still makes sense in the documentation, as we have more options of describing what a principal is.
=> feat(access): adapt document around access control

docs/meshcloud.project.md
Fix a link in meshcloud.projects in "Access Control on a meshProject" section
=> Fix a link in meshcloud.projects

docs/meshstack.azure.index.md, docs/meshstack.azure.metering.md
- fix recommended privilege escalation policy (use deny effect, prevent
all role assignments)
- remove "meshStack provisioned identities" section as we recommend
customers always use externally provisioned identities with Azure
- structure configuration setup as a guide that includes replicator
& kraken SPNs
- renamed "meshcloud AAD tenant" to "workload AAD Tenant" as this more
closely captures what the AAD tenant is meant for
- clarify instructions for setting up the EA role assignment to our SPNs
(Azure powershell module is broken and doesn't support -ObjectId parameter
for SPNs, claiming role assignments to SPNs was unsupported when it isn't)
=> feat(azure): improve azure operator documentation

docs/meshstack.gcp.index.md
this is no longer required since meshStack v7.31 and aligns setup
instructions with principle of least privilege
=> fix(gcp): remove cloud platform permission from domain wide delegation

docs/meshstack.meshmarketplace.profile.md, docs/meshstack.meshmarketplace.tenant-services.md, website/sidebars.json
- reduce duplication between metering page and profile/catalog
description
- split tenant services as a separate top-level concept page
to improve readability (profile as an overview, separate
pages to elaborate on details)
=> refactor(meshmarketplace): unify "custom" and "profile" pages

docs/meshstack.azure.index.md, docs/meshstack.configuration.md, docs/meshstack.customer-group-sync.md, docs/meshstack.gcp.index.md
Removes duplicate documentation and unifies it.
Added proper Dhall snippets from meshfed.
For now the GCP docs are not adapted as there is an open ticket which will very likly remove the impersonated user and alter config model so I dont need to document it. This must be adapted in this upcoming ticket.
=> Restructures GCP/AAD IDP config docs

docs/meshstack.configuration.md
This is the docs PR for [https://github.com/meshcloud/meshfed-release/pull/610](https://github.com/meshcloud/meshfed-release/pull/610) that implements [https://app.clickup.com/t/9wvjvq](https://app.clickup.com/t/9wvjvq)
=> Add meshfed mail docs

docs/meshcloud.payment-methods.md, docs/meshstack.tag-schema.md
Extend doc to describe that JSON schemas can now be defined for payment method tags
=> feat: JSON schema for payment methods

snippets/src/main.ts, snippets/src/sanity-check.ts
If a closing tag of a snippet was missing there was the danger of the snippet tool
removing parts of the documentation without warning. Now an error is thrown.
=> fix: Snippet tool removing docs sections

docs/meshstack.azure.index.md, docs/meshstack.customer-group-sync.md, docs/meshstack.gcp.index.md, docs/meshstack.kubernetes.config.md, docs/meshstack.kubernetes.index.md, docs/meshstack.kubernetes.landing-zones.md, docs/meshstack.kubernetes.metering.md, docs/meshstack.metadata-tags.md, docs/meshstack.openshift.metering.md, website/sidebars.json
I just realized, while writing and going through the Azure docs once more, I might have made a mistake while testing. Because in order to fetch the AKS credentals it seems the user need a special permission on the cluster resource itself. Which currently is not set via replication. I might was mislead because the user I used probably was an Admin/Owner on that resource and thus the fetching of creds just worked. Need to check that tomorrow and in that case we probably need one more replication step and I must adapt the docs.
But its quite finished beside that so I already open a draft PR.
=> feat: Adds information about the Kubernetes configuration

docs/meshstack.how-to.integrate-meshplatform-gcp-manually.md
Authorizing GCP Service Accounts for the Admin Groups API is easier to do with the Admin Console UI.
This used not to be available in the past, which is why we recommended setting it up via the Group API leveraging
the API explorer provided by Google.
=> docs: prefer GCP SA authorization via Admin Console

docs/meshstack.how-to.change-customer-owner.md
Without this fix, the YAML payload would be rejected by the server.
Signed-off-by: Marius Kießling <marius.kiessling@metro.digital>
=> fix: Move customer name to correct YAML field in owner change guide

docs/meshstack.cloudfoundry.index.md, docs/meshstack.kubernetes.index.md, docs/meshstack.openshift.index.md, docs/meshstack.openstack.index.md
I added more information around version requirements for private cloud platforms. I only added information that was retrievable with a reasonable amount of effort.
For OSB we already mention the version we support.
For public cloud platforms i don't see what should be documented around this. Mentioning some kind of root access to the platform as a prerequisite doesn't make too much sense for me. If there is additional information known by the solutions flock that should be documented, please feel free to extend this PR accordingly.
=> added more detailed version support info for private cloud platforms

docs/meshstack.how-to.get-started-with-meshstack.md, docs/meshstack.how-to.start-with-meshmarketplace.md, website/sidebars.json
* Fixed up some issues in the "how to marketplace" guide.
I think the end-user guides (the ones I moved) are a better fit to place under "User Docs -> Guides" rather than in the operator docs. I hope this makes them easier to find.
=> feat: Move user guides & more

docs/meshstack.meshmarketplace.development.md
fix instruction text around navigation to the marketplace as we notice in our workshop that it is not up to date anymore
Before:
After:
=> docs: fix instruction text around navigation to the marketplace

default.nix
@henryde not sure if this is a good idea as it essentially copies a bunch from our meshStack repo nix file and needs to be kept in sync then down the road, but i found it helpful
=> chore: add a nix file for working with meshcloud-docs

docs/meshstack.index.md, docs/meshstack.managed-service.md
- we no longer have any yaml configuration references in docs
- remove duplicate descriptions of how to access dhall configuration, move all of this to the managed-service page
=> docs: clarify meshLandingZone mapping and configuration

docs/meshstack.aws.index.md, docs/meshstack.azure.index.md, docs/meshstack.gcp.index.md, docs/meshstack.openshift.index.md
- align descriptions of capabilities supported by meshStack
- clarify language about platform connectors and self-service config
=> docs: align platform descriptions for capabilities and configuration

docs/administration.index.md
Open for any suggestion, as table seems to be quite bloated.
=> feat: add building block permissions to admin role overview

docs/meshstack.openstack.index.md
this setting has been removed since "true" is the only possible value
after the removal of meshIdB based IAM integration for OpenStack
=> docs: remove mention of federated-idp-enabled setting

amplify.yml
https://docs.meshcloud.io/robots.txt has the wrong one (develop)
For this repo our `main` branch is still called `master`.
=> fix: Wrong branch name resulting in wrong robots

amplify.yml
I gues this also proves the `AWS_BRANCH` was wrong before
=> fix: Wrong file name for robots.txt

docs/meshcloud.project-metering.md
the current link seems broken: at [this page](https://docs.meshcloud.io/docs/meshcloud.project-metering.html#exporting-chargeback-statements), when I click here:
Then I get this page:
So I changed it that it redirects to this page instead:
=> fix: fix broken link in metering

docs/meshcloud.metadata-tags.md
This feature has been rolled out a long time ago so this notice is no longer relevant to users.
=> docs: remove mention of old meshStack version

docs/meshstack.metadata-tags.md
Some usable keys were missing in the documentation for workspace related tags for the replication.
BD-528
=> fix: Adds missing metadata tag config keys

docs/meshstack.how-to.change-workspace-owner.md
Fix broken link in the section "How to change the Workspace Owner of a
meshWorkspace via API"
this is how it currently looks like on https://docs.meshcloud.io/docs/meshstack.how-to.change-workspace-owner.html:
this is how it looks like with the fix:
=> fix: fix broken link

docs/administration.building-blocks.md, docs/meshstack.how-to.create-your-own-platform.md
I am preparing the archiving of https://github.com/meshcloud/building-blocks
=> docs: update references from building-blocks to likvid-cloudfoundation

docs/meshcloud.project-metering.md
CU-86c15vwp3
I've renamed "cloud foundation team'" to "platform team" in some cases, here's the related discussion: https://meshcloud.slack.com/archives/CSLGLMN73/p1736507492578749
Also note that I didn't explicitly describe the behavior that it can happen that the chargeback is first finalized, and then updated by a new chargeback (due to our cleanup job), because I was not sure how to describe this both concisely and correctly. And imho, a short text that gives the customer clear instructions on what to do is more valuable than a huge wall of text that is hard to understand.
But if you have a suggestion on how to describe this without overwhelming the customer with too many details, I can add it.
=> feat: add info about when to process chargebacks

docs/meshcloud.platforms.md
meshcloud term is wrongly used to designate meshStack platform.
=> Replace term meshcloud with meshStack

docs/meshstack.billing-configuration.md
please merge it when we fix the currency converter https://app.clickup.com/t/86bzvvg7r
=> Currency Conversion updates

docs/administration.index.md, website/sidebars.json
I created a new "Getting Started" section at the top and moved the new get started guide + AWS S3 quickstart in there. I also plan to add the "First platform experience" in there too.
I also renamed the "Adminstration > Overview" page to "Administration > Administration Roles" as that is the only thing that page talks about.
And then I removed the "Governance" section and put all that stuff into the "Administration" section.
=> chore: Move some sidebar items around

.github/workflows/sync.yml
this workflow is used in private forks we use at meshcloud internally
to prepare documentation changes on the public repo
=> chore: add a github actions job for syncing with the upstream repo

docs/getting-started/key-concepts-guide.md
opentofu.io only shows the following content:
opentofu.io
is parked free, courtesy of GoDaddy.com.
=> fix: fix link to OpenTofu
