meshcloud/meshcloud-docs

SUMMARY.md, iaas/security.md, paas-functions-in-meshpanel.md, paas/private-domains.md
Adds documentation for adding private domains.
=> feature(doc): Adds private domain documentation

meshcloud/profile.md
=> add documentation about profile page

docs/partner.customers.md
Adds explanation how to navigate to this new feature to see the customers usage report.
=> Explains usage report of managed customer

docs/meshcloud.customer.md
It seems like someone renamed the files without taking care of the link references. There are probably more broken links throughout the documentation.
=> Fixed 404 links

docs/partner.customers.md
Fixes a messed up invitation doc.
=> fix(docs): Improves message feature docs

CONTRIBUTING.md, website/blog/2018-10-30-Release-0.md
As discussed in today's print review, we add audience personas to focus documentation and release notes.
=> Introduce audience personas

docs/meshstack.aws.md, docs/meshstack.monitoring.md, website/sidebars.json
also move metrics & monitoring to a separate page
MS-1844
=> doc: document aws external-id support

docs/administration.index.md
Sorted table to resemble role order in text. Improved naming of roles, cleaned text and added informative description about customer employee and customer admin.
=> Adapts admin and role description to the new naming scheme

docs/meshstack.azure.md
Adds the role assignment to the app to the docs.
=> fix: Adds app role assignment info

docs/meshstack.authorization.md, docs/meshstack.logging.md
=> feat: Adds docs for the 4EP configuration

docs/administration.customers.md, docs/administration.usage.md, docs/cloudfoundry.cli.md, docs/federation.index.md, docs/marketplace.service-instances.md, docs/meshcloud.customer.md, docs/meshcloud.profile.md, docs/meshcloud.service-user.md, docs/meshstack.azure.md, docs/openstack.block-storage.md, docs/openstack.cli.md, docs/openstack.object-storage.md, docs/osb.backup.md, docs/osb.volume.md
Also beautifies some text formatting.
=> fix: Removes direct links to the meshPanel

docs/meshstack.azure.md
Adds the new sync flow and explaination how to set it up
=> feat: Updates the Azure docs

docs/administration.index.md, docs/administration.landing-zones.md, docs/administration.platforms.md, docs/administration.service-brokers.md, docs/administration.usage.md, docs/marketplace.analytics.md, docs/marketplace.development.md, docs/meshcloud.groups.md, docs/meshcloud.profile.md, docs/meshcloud.project-metering.md, docs/meshcloud.project.md, docs/meshstack.identity-federation.md, docs/meshstack.index.md, docs/meshstack.osb-overview.md, docs/meshstack.platform-location.md, website/sidebars.json
- add usage report
- add landing zones
- add project user role expiry
- add platform restriction by multiple customers
- extend & update tables for functionality available to different groups
- rename Marketplace Integration -> Marketplace Development
- minor improvements
=> extend docs

docs/meshstack.kubernetes.index.md, docs/meshstack.kubernetes.metering.md, docs/meshstack.openshift.index.md, docs/meshstack.openshift.metering.md
- also remove duplicated OpenShift Landing Zone documentation
=> add OpenShift Metering documentation

docs/meshstack.meshmarketplace.metering.md
=> feat(docs): add csv export description

docs/meshstack.aws.index.md, docs/meshstack.aws.landing-zones.md, docs/meshstack.azure.index.md, docs/meshstack.configuration.md
Adds AWS and Azure account/group alias pattern options.
=> Adds Azure Subscription and Groupd customizations options

docs/meshstack.configuration.md
=> feat: document customer default quota configuration

docs/meshstack.azure.landing-zones.md
=> feat: Add docu on User Assigned Managed Identities

docs/meshstack.aws.metering.md, website/sidebars.json
aws metering configuration documentation
=> feat: document aws metering configuration

docs/meshstack.aws.landing-zones.md, docs/meshstack.azure.index.md, docs/meshstack.azure.landing-zones.md
Adds info about role mapping via Landing Zone.
=> feat: Adds documentation about the role mapping

docs/meshcloud.tenant.md
Added docs for the new meshTenant list
=> feat: Add documentation for meshTenant list

docs/administration.index.md
there's already a "Performance Analytics" row in the table
=> doc: remove duplicate Performance KPI row

docs/meshstack.managed-service.md
=> feat(managed-service): document release process and versioning

docs/meshstack.azure.index.md
=> feat(azure): clarify reduced azure permissions

docs/meshstack.configuration.md
Adds information about customer user role configuration options.
=> feat: User role config

docs/meshstack.managed-service.md
=> Some minor clarifications and typo fixing

docs/meshstack.configuration.md, website/package.json, website/yarn.lock
=> doc(panel): document updated registration configuration

docs/meshstack.aws.landing-zones.md
=> feat(aws): add AccountId and AccountArn parameters

docs/meshstack.aws.landing-zones.md, docs/meshstack.gcp.landing-zones.md
Also improves AWS lambda docs.
=> feat(gcp): Adds GCP role mapping docs

docs/meshstack.meshmarketplace.custom.md
adds clarity to description (bind resource is already mentioned later)
=> doc: add addtional link to bind resource object definition

docs/meshstack.authorization.md, docs/meshstack.configuration.md
=> doc: document project role configuration using snippet

docs/meshstack.azure.index.md
permissions to Replicator SPP
#CU-6gaafc
=> feat/fix(azure spp): Clean-up docu on Azure SPPs and add missing

docs/meshstack.gcp.index.md
Document the setup for a billing account that is owned by a different organization.
=> feat: GCP billing account from different organization

README.md, snippets/src/main.ts
also provide documentation for how to generate the snippets
=> feat(snippets): simplify invocation of snippets tool

docs/meshcloud.index.md
previously they were rendered all on the same line in html
=> fix: render supported browsers as list

docs/meshstack.authorization.md, docs/meshstack.billing.md, docs/meshstack.configuration.md, docs/meshstack.gcp.index.md
apparently forgot some during rebase of pr #235
=> refactor: regenerate all snippets, use dhall language blocks

docs/meshcloud.project-metering.md, docs/meshstack.billing.md
- added payment properties
Concerns CU-6yjzzj
=> extend documentation around chargeback statement billing info

docs/meshstack.azure.config.md, docs/meshstack.billing.md, docs/meshstack.gcp.index.md, docs/meshstack.gcp.metering.md
Seems some snippets were updated in dhall but public docs were not updated with those
=> fix: synced snippet changes to public docs

docs/administration.landing-zones.md
=> feat(docs): add missing meshLZ tags docs

website/siteConfig.js, website/static/css/custom.css
This is important because before we did not have any styling for header
rows, making it impossible for them to be distinguished from regular
rows
=> feat(style): Add some basic styling for tables

docs/meshstack.azure.landing-zones.md, docs/meshstack.tag-schema.md
Sorts docs a bit and smaller improvements in type case.
Concerns: CU-82wm66
=> feat(gcp): Adds GCP tags docs

docs/meshstack.gcp.index.md
Adds info on how to add user with group admin role.
Concerns: CU-7uw4e9
=> feat: Removes GCP domain delegation guide

docs/meshstack.openshift.index.md
- change from using meshIdB to using Enterprise IdP
- add commands for retrieving Service Account Token
- fix missing namespace in one ServiceAccount configuration
=> enhance OpenShift Platform Configuration

docs/meshstack.azure.landing-zones.md
=> feat(azure): Adds permission desc for UAMI BPs

docs/meshcloud.customer.md
Feature is not complete yet, just creating the docs while waiting for some input.
The table now looks like follows
=> feat: Customer Owner

docs/meshstack.gcp.index.md, docs/meshstack.gcp.metering.md
Adds additional rights for GCP tenant billing.
=> feat: Adds kraken GCP rights

docs/meshstack.gcp.index.md
Doc PR for [https://github.com/meshcloud/meshfed-release/pull/629](https://github.com/meshcloud/meshfed-release/pull/629)
=> Update group name pattern snippet

docs/meshstack.billing.md, docs/meshstack.customer-group-sync.md, docs/meshstack.gcp.index.md
This also included other snippets when running the `update-snippets` script
=> doc: update snippets for kraken api statement

docs/administration.customers.md, docs/administration.landing-zones.md, docs/administration.mesh-policies.md, docs/administration.projects.md, docs/meshcloud.customer.md, docs/meshcloud.metadata-tags.md, docs/meshcloud.payment-methods.md, docs/meshcloud.policies.md, docs/meshcloud.project-metering.md, docs/meshcloud.project.md, docs/meshcloud.tenant.md, docs/meshstack.azure.landing-zones.md, docs/meshstack.billing.md, docs/meshstack.gcp.landing-zones.md, docs/meshstack.metadata-tags.md, website/sidebars.json
- also did some clean ups in file names for "tag" pages
=> added meshUser/Group policies & user default tags

docs/meshstack.billing-configuration.md
I followed  a similar format as seen in https://docs.meshcloud.io/docs/meshstack.openstack.metering.html
=> landing zone fees

docs/meshstack.meshmarketplace.metering.md, docs/meshstack.meshmarketplace.metrics-metering.md, docs/meshstack.meshmarketplace.profile.md, website/sidebars.json
This documentation is mainly based on @pubudug's proposal document. I mainly did some restructuring and some smaller extensions and adaptions. Please try to review it today so we can merge and complete it today :)
=> documentation about metrics-based marketplace metering

docs/meshstack.meshmarketplace.metrics-metering.md
This is related to https://github.com/meshcloud/meshfed-release/pull/881
=> docs(metrics-metering): update docs on SamplingCounters

docs/meshstack.billing-configuration.md
https://app.clickup.com/t/auvhnw
=> Adds chargeback statement waiting period explanation.

website/siteConfig.js
=> Add link to api docs.

docs/meshstack.aws.metering.md
https://app.clickup.com/t/acxdvk
=> doc(aws): add details in metering setup

docs/meshstack.authorization.md, docs/meshstack.azure.config.md, docs/meshstack.azure.index.md, docs/meshstack.configuration.md, docs/meshstack.gcp.metering.md, docs/meshstack.metadata-tags.md
It seems like the DHALL snippets in the docs was not updated. Not all changes are done by me with the intention of this PR. So beware if it looks a bit "messy".
=> Updates the information regarding EA provisioning account setup

docs/meshstack.openstack.index.md, docs/platforms.openstack.md
=> feat(docs): added federated idp comment

docs/meshstack.openstack.index.md
=> fix(docs): fixed headers and info box styling

docs/meshstack.aws.metering.md
Screenshot of how it looks attached
[screenshot-localhost_3000-2021.06.08-10_14_00.pdf](https://github.com/meshcloud/meshcloud-docs/files/6614691/screenshot-localhost_3000-2021.06.08-10_14_00.pdf)
=> feat: cost explorer integration

docs/meshstack.openstack.inventory.md, website/sidebars.json
=> feat: open stack offline status

docs/meshstack.meshmarketplace.metrics-metering.md
vw sent periodicCounter in the response which caused the mentioned error
=> fix: Fix for error Service Broker catalog defined metricType '$metricType', which is not supported

.github/dependabot.yml, .kodiak.toml
For decision see
https://www.notion.so/meshcloud/Developer-Conventions-cfa4d3b27b4042699b96068c0a817ea5#1d90ecede2454bf0a5f18f9d7569b576
=> feature: automerge dependabot PRs

docs/meshstack.azure.landing-zones.md
=> feat: Adds warning against TF usage for Azure function setup

docs/meshstack.identity-lookup.md
https://github.com/meshcloud/meshcloud-docs/pull/412/files#r704130203
=> fix: review comment fix on earlier PR

docs/meshstack.user-group-provisioning.md, website/sidebars.json
=> feat: add section for user / group provisioning

docs/administration.customers.md, docs/meshstack.identifiers.md, docs/meshstack.onboarding.md
Related to https://github.com/meshcloud/meshfed-release/pull/1974
=> refactor: Removed unused configuration from docs

docs/meshstack.metadata-tags.md
The tenantPlatformNumber is now also exposed to Lambdas
and cloud functions.
=> feat: Adds tenantPlatformNumber desc to parameter

website/siteConfig.js
this is required to generate the correct URL for sitemaps.xml
right now we emit the wrong URL, leading to search engine
indexing errors
=> fix: set website url correctly

docs/meshstack.aws.index.md, docs/meshstack.azure.index.md
- Includes guiding the reader to use terraform
- Includes directing the reader to our cloudfoundation building block for federated identities
- Includes some restructuring
=> chore: edit azure integration docs

docs/administration.mesh-policies.md, docs/meshcloud.policies.md
=> feat: removed multiple policy rule assignment

docs/meshstack.gcp.metering.md
https://app.clickup.com/t/96tafb
=> GCP Kraken Permissions

docs/meshstack.how-to.integrate-meshplatform-azure-manually.md
https://app.clickup.com/t/96pd6a
=> Retained Subscription Owner

docs/meshcloud.metadata-tags.md, docs/meshstack.metadata-tags.md
=> feat: added immutable tags section

website/core/Footer.js, website/pages/en/help.js, website/pages/en/index.js
=> fix: Fix 404 errors by removing language distinction.

docs/meshcloud.policies.md
Improvement on not crossing lines and spelling 
CU-1ydq6ew
=> fix: fix spelling and improve graph

docs/administration.mesh-policies.md
=> feat: add optioanl desription and how to fix section in policies

docs/meshstack.identity-lookup.md
=> Fixed a few readable issues in identity-lookup.

docs/administration.mesh-policies.md, docs/meshcloud.policies.md, docs/meshstack.metadata-tags.md
Final adaption of the section related to the meshPolicyTransparency CR
CU-1y28743
=> feat: round off meshPolicy docs rework

docs/meshcloud.policies.md
Improve because unclear in team
=> feat: improve policy evaluation strategy section

docs/administration.meshstack-settings.md, website/sidebars.json
=> feat: added meshStack Settings

docs/administration.landing-zones.md, docs/meshstack.meshmarketplace.profile.md, docs/meshstack.meshmarketplace.tenant-services.md, website/sidebars.json
* Still to-do: describe workaround for non-tenant-services
=> Describe admin side of tenant services.

website/blog/2019-03-07-Release-0.md, website/blog/2020-04-22-Release-0.md, website/blog/2020-09-18-Release-0.md, website/blog/2020-10-29-Release-0.md, website/sidebars.json
```
Page URL,HTTP Code,Discovered
https://docs.meshcloud.io/blog/2020/09/18/2020-09-11-Release-0.md,404,04 Jun 2022 (02:16 UTC)
https://docs.meshcloud.io/blog/2020/09/18/2020-09-21-Release-0.md,404,04 Jun 2022 (02:16 UTC)
https://docs.meshcloud.io/blog/page14/2020-09-11-Release-0.md,404,29 Oct 2022 (04:48 UTC)
https://docs.meshcloud.io/blog/page14/2020-09-21-Release-0.md,404,29 Oct 2022 (04:48 UTC)
https://docs.meshcloud.io/docs/meshcloud.tag-schema.html,404,04 Jun 2022 (02:16 UTC)
https://docs.meshcloud.io/docs/meshstack.aws.html,404,04 Jun 2022 (02:16 UTC)
https://docs.meshcloud.io/docs/meshstack.how-to.confirm-project-deletion.html,404,18 Jun 2022 (02:54 UTC)
https://docs.meshcloud.io/docs/meshstack.tag-schema.html,404,04 Jun 2022 (02:16 UTC)
```
=> chore: Fix broken links reported by Semrush

docs/meshstack.user-group-provisioning.md
This will only be merged once we have fully implemented and released the deletion and deactivation.
=> SCIM extend docs about deactivation and permissions management

docs/administration.emergency-users.md, docs/administration.landing-zones.md, docs/administration.mesh-policies.md, docs/administration.projects.md, docs/administration.workspaces.md, docs/faq.projects.md, docs/meshcloud.budget-alerts.md, docs/meshcloud.index.md, docs/meshcloud.landing-zones.md, docs/meshcloud.payment-methods.md, docs/meshcloud.project-metering.md, docs/meshcloud.project-resources.md, docs/meshcloud.project.md, docs/meshcloud.tenant.md, docs/meshcloud.workspace.md, docs/meshstack.authorization.md, docs/meshstack.how-to.change-workspace-owner.md, docs/meshstack.how-to.create-project.md, docs/meshstack.how-to.create-workspace-via-api.md, docs/meshstack.how-to.delete-meshObjects.md, docs/meshstack.how-to.onboard-team-to-project.md, docs/meshstack.how-to.onboard-team-to-workspace.md, docs/meshstack.identity-federation.md, docs/meshstack.identity-lookup.md, docs/meshstack.meshmarketplace.development.md, docs/meshstack.onboarding.md, docs/meshstack.workspace-group-sync.md
=> feat: replace customer roles by workspace roles

docs/meshstack.how-to.integrate-meshplatform-azure-manually.md
Azure JSON validator fails otherwise
=> Remove superflous comma

.github/workflows/release.yml
=> ci: add write permission to release.yml

docs/meshstack.meshmarketplace.development.md
* adapt Marketplace term to Service Brokers
=> feat: adapt docs to new service instances filter functionality

docs/administration.delete-tenants.md, docs/meshstack.openstack.index.md
this workflow drops support for resource existence checks
=> docs: update to reflect simplified tenant deletion workflow

docs/administration.dns.md, website/sidebars.json
@henryde @malhussan Did I forget an endpoint in that list?
=> dns and ssl

docs/meshstack.replication-configuration.md
=> feat: Adds uniqueness notes for naming pattern

docs/meshstack.how-to.integrate-meshplatform-azure-manually.md
@tfelix already provided the functionality 2024.25.0
=> chore: mca now supports using equal source and destination tenant

website/siteConfig.js
=> chore: color

docs/meshstack.billing-configuration.md
See the discussion in the following PR for context: https://github.com/meshcloud/meshfed-release/pull/6597#discussion_r1756459231
=> fix: remove metadata keys that are no longer relevant

docs/meshstack.metadata-tags.md
=> fix: Incorrect name for landing zone tag name

docs/meshstack.metadata-tags.md
=> chore: add new tag to docs

docs/meshstack.github.pipeline-automation.md
=> chore: give an example how a dispatch event looks like

docs/meshstack.identity-federation.md, docs/meshstack.identity-lookup.md, docs/meshstack.workspace-group-sync.md
minor changes to defaults and customer -> workspace renames
=> docs: sync docs snippets with config model

docs/meshstack.building-blocks.meshStack-http-backend.md, website/sidebars.json
CU-86c1waw1y
https://pr-1008.d17q6gob2fx97d.amplifyapp.com/docs/meshstack.building-blocks.meshStack-http-backend.html
=> docs for meshstack http backend

.github/instructions/tone.instructions.md, docs/new-integration-how-to-integrate-aws.md, docs/new-integration-how-to-integrate-azure-administrative-units.md, docs/new-integration-how-to-integrate-azure.md, sidebars.ts
- Link AU guide from main Azure integration documentation
- Add AU guide to sidebar navigation under Microsoft Azure section
=> docs: add Azure Administrative Units integration guide

docs/new-concept-buildingblock.md, docs/new-guide-how-to-launch-a-new-manual-building-block.md, docs/new-guide-how-to-launch-a-new-terraform-building-block.md, sidebars.ts
* these were sent over by Slack
=> chore: More guides from Rebecca
